language: r
sudo: false
cache: packages

dist: xenial
addons:
  apt:
    sources:
      - sourceline: 'ppa:cran/v8'
    packages:
      - libnode-dev

matrix:
  include:
   - r: 3.2
   - r: 3.3
   - r: 3.4
   - r: 3.5
   - r: release
   - r: devel

after_success:
  - test $TRAVIS_R_VERSION_STRING = "release" && Rscript -e 'covr::codecov()'
